- user/blender.md
info on what is and isn't supported with BlenderBIM
closes #3
> feat(user): blender bim info

- .vuepress/config.js
- dev/server-stream-previews.md
https://speckle.community/t/how-to-fetch-the-icon-of-the-stream/1698/9
> feat(dev): preview img url scheme

- user/sketchup.md
- user/support-tables.md
since v2.0.5, this is no longer an issue 😉
> feat(sketchup): update to remove receive warnings!

- dev/py-examples.md
I put this up as an issue, I just figured I would go ahead and send a PR for this too
> update key from obj_id to object_id

- dev/base.md
> Updated reference to now obsolete displayMesh

- user/ui2.md
my best guess at what was meant to be said?
> Typos in Commit message section

- dev/base.md
- dev/server-webhooks.md
Committing to a stream in response to a webhook event triggered by commits is a 🤦
> docs(server): Added warning about triggering infinite loops with Webhooks

- user/support-tables.md
> Updates support for tin surfaces in civil3d 

- user/FAQs.md
- user/dynamo.md
- user/excel.md
Updated documentation pages for Dynamo and Excel connectors and FAQs with general fixes for typos and comments.
> Update dynamo.md, excel.md, and FAQs documentation pages

- dev/apps.md
- dev/base.md
- dev/decomposition.md
Updated apps.md, base.md, and decomposition.md documentation pages with fixes for typos, comments, and code.
> Update apps.md, base.md, and decomposition.md pages

- dev/FilteringData.md
- dev/js.md
- dev/server-manualsetup.md
- dev/server-setup-k8s.md
Updated FilteringData.md, js.md, and server documentation pages with fixes for typos and code samples/snippets.
> Update FilteringData.md, js.md, and server documentation

- user/autocadcivil.md
- user/bentley.md
- user/connectors.md
- user/csi.md
Updated AutoCAD, Bentley, and CSI connector documentation pages with general fixes for typos and comments.
> Update pages for AutoCAD, Bentley, and CSI connectors

- dev/dotnet.md
Change from "streamId" to streamId.
> fix small problem with code .NET

- .vuepress/config.js
- user/connectors.md
- user/navisworks.md
- user/support-tables.md
Adds Navisworks support tables, guides for installation and operation and updates the contents list.
> Add Navisworks

- user/powerbi/using-powerbi-connector.md
- user/powerbi/working-with-records.md
- Added two more videos to Working with Records page
- Escaped markdown syntax on [Structured](beta)
> Working with Records videos

- user/support-tables.md
Re: [https://github.com/specklesystems/speckle-sharp/pull/3023](https://github.com/specklesystems/speckle-sharp/pull/3023)
> Update support-tables.md with Revit Rebar

- .vuepress/config.js
- .vuepress/public/admin/config.yml
- README.md
- automate/README.md
- automate/create-automation.md
- automate/create-function.md
- automate/function-specification.md
- automate/register-existing-function-repository.md
- automate/release-function-version.md
- automate/update-automation.md
- dev/README.md
Includes user documentation for working with both Automations and Functions.
Also includes a technical specification for Functions.
> feat(automate): initial documentation for automate

- dev/server-manualsetup.md
Adding NUXT_PUBLIC_BASE_URL to server-manualsetup.md
> Update server-manualsetup.md with NUXT_PUBLIC_BASE_URL

- .vuepress/config.js
- viewer/acceleration-structure-api.md
- viewer/batch-api.md
- viewer/batch-object-api.md
- viewer/camera-controller-api.md
- viewer/extension-api.md
- viewer/intersections-api.md
- viewer/measurements-tool-api.md
- viewer/migration-guide.md
- viewer/queries-api.md
- viewer/render-tree-api.md
- viewer/render-view-api.md
- viewer/section-tool-api.md
- viewer/section-tool-outlines-api.md
- viewer/selection-extension-api.md
- viewer/speckle-renderer-api.md
- viewer/top-level-acceleration-structure-api.md
- viewer/viewer-api.md
- viewer/world-tree-api.md
- Added transform and transformInv to BatchObject. 
- Added important clarification to computeTransform in RenderTree
> Viewer updates

- viewer/camera-controller-api.md
> Fixed typo

- .vuepress/config.js
- viewer/intersections-api.md
- viewer/loading-example.md
- viewer/migration-guide.md
- viewer/render-tree-api.md
- viewer/smooth-orbit-controls-api.md
- viewer/speckle-controls-api.md
- Updated migration guide to latest version.
- Updated API reference with the latest changes. 
- Added the new SpeckleControls and SmoothCameraControls classes
> Viewer Navigation Updates

- viewer/camera-controller-api.md
- viewer/loading-example.md
- viewer/speckle-controls-api.md
Small update after https://github.com/specklesystems/speckle-server/pull/2475
> Viewer Docs Updates

- .vuepress/config.js
- automate/README.md
- automate/important-caveats.md
- adds generic intro for people with no context on automate
- removes roadmap
- moves troubleshooting section
> minor touches

- viewer/README.md
Resolve issue at https://github.com/specklesystems/speckle-docs/issues/258
> Update link broked in README.md

- .vuepress/config.js
Removed Viewer related docs that do not apply anymore and just confuse users
> Removed old viewer docs

- viewer/selection-extension-api.md
- viewer/speckle-renderer-api.md
- Specified and described the `SelectionExtension` mechanism of caching and applying materials
- Added optional `force` parameter to `updateShadowcatcher`
> Small updates to viewer docs

- .vuepress/config.js
- user/concepts.md
- workspaces/billing.md
- workspaces/data-residency.md
- workspaces/getting-started.md
- workspaces/members.md
- workspaces/projects.md
- workspaces/roles.md
- workspaces/sso.md
- workspaces/welcome-to-workspaces.md
Updates various pages in the workspaces docs. Many things can still be improved but at least it should now all be accurate.
> Update workspace documentation

- dev/quickstart.md
- dev/server-manualsetup.md
- dev/server-setup-k8s.md
Part of https://linear.app/speckle/project/migrate-redis-to-valkey-bf792730a45c/overview
We are replacing Redis with the Redis-compatible Valkey
> chore(dev): replace redis with valkey

- .devcontainer/.zshrc
- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .dockerignore
Adds a devcontainer configuration for the project.
This allows for a consistent and reproducible development environment using Docker.
Includes:
- Dockerfile for building the container.
- Configuration to automatically install dependencies.
- Zsh configuration with oh-my-zsh and custom aliases.
- VS Code settings and extensions.
> Adds devcontainer configuration

- .vuepress/config.js
- viewer/measurements-tool-api.md
- viewer/migration-guide.md
- viewer/rendering-pipeline-api/README.md
- viewer/rendering-pipeline-api/pipeline-api.md
- viewer/section-tool-api.md
- Updated section tool docs
- Updates measurements tools docs
- Updated rendering pipeline API docs
- Updated migration guide
> Alex/viewer updates 22.25.7
